[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.8", features = ["ws", "multipart"] }
anyhow = "1.0.95"
chrono = { version = "0.4.39", features = ["serde"] }
dotenvy = "0.15.7"
futures-util = "0.3.32"
redis = { version = "0.27", features = ["tokio-comp", "cluster-async"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "macros", "chrono", "json"] }
tokio = { version = "1.50.0", features = ["full"] }
tower = "0.5.3"
tower-http = { version = "0.6.8", features = ["cors", "fs", "trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
aes-gcm = "0.10.3"
aead = { version = "0.5.2", features = ["rand_core"] }
base64 = "0.22.1"
reqwest = { version = "0.13.2", features = ["json"] }
rand = "0.8.5"
ed25519-dalek = "2.1"
hex = "0.4.3"
